cute/config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :images do
	resources :posts, shallow: true
  end
  patch 'image/:id/yes_vote' => 'images#yes_vote'
  patch 'image/:id/no_vote' => 'images#no_vote'

root 'images#index'
end

cute/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :posts
	def generate_filename
		self.filename = (0...15).map { (65 + rand(26)).chr }.join + ".jpg"
		if Image.find_by(filename: self.filename) !=nil
		generate_filename
		end
	end
	def percent_cute
		(self.cute_vote.to_f/self.total_vote.to_f).to_f
	end

	def random_self
		(Image.all - self).map{|image| image if image.img_type == self.img_type and image.id != self.id}.compact!.sample
	end

end

cute/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
end

cute/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :images
end

cute/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

      protected
          def configure_permitted_parameters
              devise_parameter_sanitizer.for(:sign_up) << :username
              devise_parameter_sanitizer.for(:account_update) << :username
          end
end

cute/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @display_dog = Image.all.map{|x| x if x.img_type == "Dog"}.compact!.sample
    @display_cat = Image.all.map{|x| x if x.img_type == "Cat"}.compact!.sample
    @display_baby = Image.all.map{|x| x if x.img_type == "Baby"}.compact!.sample
    @display_reptile = Image.all.map{|x| x if x.img_type == "Reptile"}.compact!.sample
    @display_horse = Image.all.map{|x| x if x.img_type == "Horse"}.compact!.sample
    @display_hedgehog = Image.all.map{|x| x if x.img_type == "Hedgehog"}.compact!.sample
    @display_bird = Image.all.map{|x| x if x.img_type == "Bird"}.compact!.sample
    @display_rodent = Image.all.map{|x| x if x.img_type == "Rodent"}.compact!.sample
  end

  # GET /images/1
  # GET /images/1.json
  def show
	@post = @image.posts.new
	@image = Image.find(params[:id])
	if @image.total_vote > 0
		@cute_percent = (@image.cute_vote.to_f/@image.total_vote.to_f*100.00).to_i
	else
		@cute_percent = 0
	end
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
     @image = Image.new(image_params)
     @image.cute_vote = 0
     @image.total_vote = 0
	@image.generate_filename
	@image.user = current_user
	@uploaded_io = params[:image][:uploaded_file]
	if @uploaded_io != nil
		File.open(Rails.root.join('public','images',@image.filename), 'wb') do |file|
			file.write(@uploaded_io.read)
		end

		if @image.save
			redirect_to @image, notice: 'Image was successfully created'
		else
			render :new
		end
	else
		@image.destroy
		index
	end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
	@uploaded_io = params[:image][:uploaded_file]
	@image.img_type = params[:img_type]
	if @uploaded_io != nil
		File.open(Rails.root.join('public','images',@image.filename), 'wb') do |file|
			file.write(@uploaded_io.read)
		end

		if @image.save
			redirect_to @image, notice: 'Image was updated'
		else
			render :new
		end
	else
		@image.save
		redirect_to @image, notice: 'Image was updated'
        end
  end

  def yes_vote
	@image = Image.find(params[:id])
	@image.cute_vote = @image.cute_vote + 1
	@image.total_vote = @image.total_vote + 1
	@image.save
	@dice = Image.all.map{|x| x if x.img_type == @image.img_type and x.id != @image.id}.compact!.sample
	if @dice == nil
	redirect_to root_url
	else
	redirect_to @dice
	end
  end

  def no_vote
	@image = Image.find(params[:id])
	@image.total_vote = @image.total_vote + 1
	@image.save
	@dice = Image.all.map{|x| x if x.img_type == @image.img_type and x.id != @image.id}.compact!.sample
	if @dice == nil
	redirect_to root_url
	else
	redirect_to @dice
	end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:filename, :img_type, :cute_vote, :total_vote, :user_id)
    end
end

cute/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
	@image = Image.find params[:image_id]
  	@post = @image.posts.new(post_params)
	@post.user_id = current_user
	@post.username = current_user.username

	if @post.save
		redirect_to @image, notice: 'Comment posted'
	else
		render :new
	end

  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:comment, :image_id, :user_id, :posted)
    end
end

cute/app/helpers/application_helper.rb
module ApplicationHelper
end

cute/app/helpers/images_helper.rb
module ImagesHelper
end

cute/app/helpers/posts_helper.rb
module PostsHelper
end

cute/app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
 <%= f.file_field :uploaded_file %>
<br>
<br>
Catagory:
  <%=f.select :img_type, options_for_select([["Dog"], ["Cat"],["Horse"],["Reptile"],["Hedgehog"],["Rodent"],["Baby"],["Bird"]])%>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cute/app/views/images/_no_vote.html.erb
<%= form_for(image, url: {controller: "images", action: "no_vote", id: image.id.to_s}) do |f|%>
	<%= f.submit"Not"%>
<%end%>

cute/app/views/images/_yes_vote.html.erb
<%= form_for(image, url: {controller: "images", action: "yes_vote", id: image.id.to_s}) do |f|%>
	<%= f.submit"Cute"%>
<%end%>

cute/app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>
<%= link_to 'Delete', @image, method: :delete %>
<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

cute/app/views/images/index.html.erb
<h1>Cute or Not</h1>
<%if user_signed_in?%>
<%= link_to 'New Image', new_image_path %>
<%end%>
<h3> What do you want to look at?</h3>
<table style ="width:100%" border="1">

  <tbody>
      <tr>
<td><center><strong>Dogs</strong></td>
<td><center><strong>Cats</strong></td>
<td><center><strong>Horses</strong></td>
<td><center><strong>Rodents</strong></td>
      </tr>
      <tr>
<td><center><%= link_to image_tag(root_url + "images/" + @display_dog.filename, size: "100x100"), @display_dog%></td>
<td><center><%= link_to image_tag(root_url + "images/" + @display_cat.filename, size: "100x100"), @display_cat%></td>
<td><center><%= link_to image_tag(root_url + "images/" + @display_horse.filename, size: "100x100"), @display_horse%></td>
<td><center><%= link_to image_tag(root_url + "images/" + @display_rodent.filename, size: "100x100"), @display_rodent%></td>
      </tr>
	<tr>
<td><center><strong>Hedgehogs</strong></td>
<td><center><strong>Birds</strong></td>
<td><center><strong>Babies</strong>
<td><center><strong>Reptiles</strong></td>
	</tr>
	<tr>
<td><center><%= link_to image_tag(root_url + "images/" + @display_hedgehog.filename, size: "100x100"), @display_hedgehog%></td>
<td><center><%= link_to image_tag(root_url + "images/" + @display_bird.filename, size: "100x100"), @display_bird%></td>	
<td><center><%= link_to image_tag(root_url + "images/" + @display_baby.filename, size: "100x100"), @display_baby%></td>	
<td><center><%= link_to image_tag(root_url + "images/" + @display_reptile.filename, size: "100x100"), @display_reptile%>
	</tr>
  </tbody>
</table>

cute/app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

cute/app/views/images/show.html.erb
<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>
<p id="notice"><%= notice %></p>


<center><table border ="2" style="width:20%">
<%= render 'yes_vote', image: @image %>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<strong><%= @cute_percent%>
% cute</strong>
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<%= render 'no_vote', image: @image %></div><br>
<td><center><%= image_tag root_url + "/images/" + @image.filename, size: "500x550", alt: @image.filename %><br>
</td></center>
</table>
<%if user_signed_in?%>
	<%if @image.posts.length == 0 %>
		No comments on this image yet, be the first!
		<%= render 'posts/form'%>
	<%else%>
	<table border="1" style="width:100%">
<tr style="background-color:lightgray">
	<td><strong>Poster</td>
	<td><strong>Comment</td>
	<td><strong>Dated Posted</td>
</tr>
		<%@image.posts.each do |post|%>
<tr>
			<%if !post.new_record? %>	
			<td>Posted by: <%=post.username%></td>
			<td><%=post.comment%></td>
			<td>Posted on: <%=post.created_at%></td>
			<%end%>
		<%end%>
	<br>
	<%= render 'posts/form'%>
	<%end%>
</table>
<%end%>

cute/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%#the following two lines is used for adding devise user log in/log out buttons to each page%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div id="user_nav">
<% if user_signed_in? %>
Signed in as <%= current_user.username %>. Not you?
<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign up", new_user_registration_path %> or
<%= link_to "Sign in", new_user_session_path %>
<% end %>
</div>
  <title>Cute</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

cute/app/views/posts/_form.html.erb
<%= form_for([@image, @post]) do |f| %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cute/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

cute/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Image</th>
      <th>User</th>
      <th>Posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.comment %></td>
        <td><%= post.image %></td>
        <td><%= post.user %></td>
        <td><%= post.posted %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

cute/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

cute/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @post.comment %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Posted:</strong>
  <%= @post.posted %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>